# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: format
        name: Format Rails code
        entry: bin/fmt
        language: ruby
        pass_filenames: false
        types: [ruby]
        stages: [pre-commit]

    -   id: test
        name: Run Rails tests
        entry: bin/rails test
        language: ruby
        pass_filenames: false
        types: [ruby]
        stages: [pre-commit]

    -   id: prepush
        name: Rails pre-push checks
        entry: bin/prepush
        language: ruby
        pass_filenames: false
        types: [ruby]
        stages: [pre-push]
